### ISSUE TITLE
Suggestion: Option to hide overlay after x amount of time

### ISSUE THREAD

**Issue by andrellvs** [madmodder123/retropie_music_overlay#1]
It might be interesting to include in the code an image duration time, with the name of the current song, which is on the screen. Because she does not leave the screen.

**Comment by madmodder123** [comment]
Good ideas, i'll try to do this when I have free time

**Comment by madmodder123** [comment]
> 
> 
> It might be interesting to include in the code an image duration time, with the name of the current song, which is on the screen. Because she does not leave the screen.

This feature has been added!
